display_name: avee

packager: avee
packagerEmail: info@aveevpn.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - avee
  - Clash
    - Proxy

generic_name: avee

group: Applications/Internet

startup_notify: true