display_name: avee
package_name: avee
maintainer:
  name: avee
  email: info@aveevpn.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - avee
  - Clash
  - ClashMeta
  - Proxy

generic_name: avee

categories:
  - Network

startup_notify: true